### PR TITLE
shut down with error on ledger crash

### LINKED ISSUE #512: fix ledger crash process exit status
A panic inside ledger's shell is not properly propagated to the process status - it shuts down, but exits with success

### PR DESCRIPTION
**Pull request by tzemanovic**
closes #512

### CODE REVIEW

File: apps/src/lib/node/ledger/tendermint_node.rs [hunk 1]
```diff
@@ -141,9 +149,9 @@ fn monitor_process(
     kill_switch: Sender<bool>,
```
Comment (yito88) [inline apps/src/lib/node/ledger/tendermint_node.rs:149]: For consistency, `kill_switch` can be replaced with `abort_sender`

Comment (tzemanovic) [reply apps/src/lib/node/ledger/tendermint_node.rs]: done

**Review by yito88 — APPROVED** [review]
Looks good!
